import { Flex } from "@chakra-ui/react";
import Head from "next/head";
import TableComponent from "../components/Table";
import Header from "../components/Header";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <main className="flex flex-col p-4">
        <TableComponent />
      </main>

      <Flex>Powered by 🧨 Contechs</Flex>
    </div>
  );
}
